ecommerce/core/urls.py
from django.urls import path, include

from .views import index, contact, cart, checkout, detail, shop, search, search_auto

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
    path('contact/', contact, name='contact'),
    path('cart/', cart, name='cart'),
    path('checkoout/', checkout, name='checkout'),
    path('shop/', shop, name='shop'),
    path('search/', search, name='search'),
    path('search_auto/', search_auto, name='search_auto'),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('p/', include('product.urls')),
    path('order/', include('order.urls')),
    path('user/', include('users.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/core/models.py
from django.db import models
from django.utils.safestring import mark_safe
from ckeditor.fields import RichTextField
from django.forms import ModelForm
from django import forms


# Create your models here.
class Setting(models.Model):
    STATUS = (
        ('True', 'True'),
        ('False', 'False'),
    )
    title = models.CharField(max_length=150)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    company = models.CharField(max_length=50)
    address = models.CharField(blank=True, max_length=100)
    phone = models.CharField(blank=True, max_length=15)
    fax = models.CharField(blank=True, max_length=15)
    email = models.CharField(blank=True, max_length=50)
    smtpserver = models.CharField(blank=True, max_length=50)
    smtpemail = models.CharField(blank=True, max_length=50)
    smtppassword = models.CharField(blank=True, max_length=10)
    smtpport = models.CharField(blank=True, max_length=5)
    icon = models.ImageField(blank=True, upload_to='images/')
    facebook = models.CharField(blank=True, max_length=50)
    instagram = models.CharField(blank=True, max_length=50)
    twitter = models.CharField(blank=True, max_length=50)
    youtube = models.CharField(blank=True, max_length=50)
    aboutus = RichTextField(blank=True)
    contact = RichTextField(blank=True)
    references = RichTextField(blank=True)
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class ContactMessage(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Read', 'Read'),
        ('Closed', 'Closed'),
    )
    name = models.CharField(blank=True, max_length=20)
    email = models.EmailField(blank=True, max_length=50)
    subject = models.CharField(blank=True, max_length=50)
    message = models.TextField(blank=True, max_length=255)
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=20)
    note = models.CharField(blank=True, max_length=100)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class ContactForm(ModelForm):
    class Meta:
        model = ContactMessage
        fields = ['name', 'email', 'subject', 'message']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'input', 'placeholder': 'Name & Surname'}),
            'subject': forms.TextInput(attrs={'class': 'input', 'placeholder': 'Subject'}),
            'email': forms.EmailInput(),
            'message': forms.Textarea(attrs={'class': 'input', 'placeholder': 'Your Message', 'rows': '5'}),
        }


class FAQ(models.Model):
    STATUS = (
        ('True', 'True'),
        ('False', 'False'),
    )
    ordernumber = models.IntegerField()
    question = models.CharField(max_length=200)
    answer = RichTextField()
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.question

ecommerce/core/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render

from order.models import ShopCart
from .models import Setting, ContactForm, ContactMessage
from product.models import Category, Product
import json


# Create your views here.

def index(request):
    setting = Setting.objects.filter(status=True).first()
    category = Category.objects.all()
    product_slider = Product.objects.order_by('id').all()[:3]
    products = Product.objects.order_by('id').all()
    current_shopcart = ShopCart.objects.filter(user_id=request.user.id)
    total = 0
    for sc in current_shopcart:
        total += sc.product.price * sc.quantity
    context = {
        'setting': setting,
        'category': category,
        "product_slider": product_slider,
        "products": products,
        "shopcart": current_shopcart
    }
    return render(request, 'core/index.html', context)


def contact(request):
    setting = Setting.objects.filter(status=True).first()
    category = Category.objects.all()

    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            contactMessage = ContactMessage()
            contactMessage.name = form.cleaned_data['name']
            contactMessage.email = form.cleaned_data['email']
            contactMessage.subject = form.cleaned_data['subject']
            contactMessage.message = form.cleaned_data['message']
            contactMessage.ip = request.META.get('REMOTE_ADDR')
            contactMessage.save()
            messages.success(request, 'Message Send')
            return HttpResponseRedirect('/contact/')
    form = ContactForm
    current_shopcart = ShopCart.objects.filter(user_id=request.user.id)
    total = 0
    for sc in current_shopcart:
        total += sc.product.price * sc.quantity
    context = {
        'setting': setting,
        'form': form,
        'category': category,
        "shopcart": current_shopcart
    }
    return render(request, 'core/contact.html', context)


def search(request):
    setting = Setting.objects.filter(status=True).first()
    category = Category.objects.all()
    product_slider = Product.objects.order_by('id').all()[:3]
    products = Product.objects.all()
    if request.method == 'POST':
        query = request.POST['query']
        catId = int(request.POST['cat'])
        if catId == 0:
            products = Product.objects.filter(title__icontains=query)
        else:
            products = Product.objects.filter(title__icontains=query, category_id=catId)

    current_shopcart = ShopCart.objects.filter(user_id=request.user.id)
    total = 0
    for sc in current_shopcart:
        total += sc.product.price * sc.quantity
    context = {
        'setting': setting,
        'category': category,
        "product_slider": product_slider,
        'products': products,
        'query': query,
        "shopcart": current_shopcart,
    }
    return render(request, 'core/search_results.html', context)


def search_auto(request):
    if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        q = request.GET.get('term', '')
        products = Product.objects.filter(title__icontains=q)
        results = []
        for pl in products:
            results.append(pl.title)
        data = json.dumps(results)
    else:
        data = 'fail'
    mimetype = 'application/json'
    return HttpResponse(data, mimetype)


def detail(request):
    setting = Setting.objects.filter(status=True).first()
    category = Category.objects.all()
    context = {
        'setting': setting,
        'category': category
    }
    return render(request, 'core/detail.html', context)


def cart(request):
    setting = Setting.objects.filter(status=True).first()
    category = Category.objects.all()
    context = {
        'setting': setting,
        'category': category
    }
    return render(request, 'core/cart.html', context)


def checkout(request):
    setting = Setting.objects.filter(status=True).first()
    category = Category.objects.all()
    context = {
        'setting': setting,
        'category': category
    }
    return render(request, 'core/checkout.html', context)


def shop(request):
    setting = Setting.objects.filter(status=True).first()
    category = Category.objects.all()
    context = {
        'setting': setting,
        'category': category
    }
    return render(request, 'core/shop.html', context)

ecommerce/templates/core/cart.html
{% extends 'core/layout.html' %}
{% load static %}
{% block title %} Shop Cart
{% endblock %}

{% block content %}


    <!-- Page Header Start -->
    <div class="container-fluid bg-secondary mb-5">
        <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 300px">
            <h1 class="font-weight-semi-bold text-uppercase mb-3">Shopping Cart</h1>
            <div class="d-inline-flex">
                <p class="m-0"><a href="">Home</a></p>
                <p class="m-0 px-2">-</p>
                <p class="m-0">Shopping Cart</p>
            </div>
        </div>
    </div>
    <!-- Page Header End -->


    <!-- Cart Start -->
    <div class="container-fluid pt-5">
        <div class="row px-xl-5">
            <div class="col-lg-8 table-responsive mb-5">
                <table class="table table-bordered text-center mb-0">
                    <thead class="bg-secondary text-dark">
                        <tr>
                            <th>Products</th>
                            <th>Price</th>
                            <th>Quantity</th>
                            <th>Total</th>
                            <th>Remove</th>
                        </tr>
                    </thead>
                    <tbody class="align-middle">
                        {% for sc in shopcart %}

                        <tr>
                            <td class="align-middle">
                                <img src="{{ sc.product.image.url }}" alt="" style="width: 50px;">
                                <a href="/p/products/{{sc.product.id}}/{{sc.product.slug}}">{{sc.product.title}}</a>
                            </td>
                            <td class="align-middle">{{sc.product.price}}</td>
                            <td class="align-middle">
                                <div class="input-group quantity mx-auto" style="width: 100px;">
                                    <div class="input-group-btn">
                                        <button class="btn btn-sm btn-primary btn-minus" >
                                        <i class="fa fa-minus"></i>
                                        </button>
                                    </div>
                                    <input type="text" class="form-control form-control-sm bg-secondary text-center" value="{{sc.quantity}}">
                                    <div class="input-group-btn">
                                        <button class="btn btn-sm btn-primary btn-plus">
                                            <i class="fa fa-plus"></i>
                                        </button>
                                    </div>
                                </div>
                            </td>
                            <td class="align-middle">${{sc.amount}}</td>
                            <td class="align-middle"><a href="/order/shopcart/deleteitem/{{ sc.id }}" class="btn btn-sm btn-primary" onclick="return confirm('Are you sure delete? {{ sc.product.title }} from shopcart')"><i class="fa fa-times"></i></a></td>
                        </tr>

                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-lg-4">
                <form class="mb-5" action="">
                    <div class="input-group">
                        <input type="text" class="form-control p-4" placeholder="Coupon Code">
                        <div class="input-group-append">
                            <button class="btn btn-primary">Apply Coupon</button>
                        </div>
                    </div>
                </form>
                <div class="card border-secondary mb-5">
                    <div class="card-header bg-secondary border-0">
                        <h4 class="font-weight-semi-bold m-0">Cart Summary</h4>
                    </div>
                    <div class="card-body">
<!--                        <div class="d-flex justify-content-between mb-3 pt-1">-->
<!--                            <h6 class="font-weight-medium">Subtotal</h6>-->
<!--                            <h6 class="font-weight-medium">$150</h6>-->
<!--                        </div>-->
<!--                        <div class="d-flex justify-content-between">-->
<!--                            <h6 class="font-weight-medium">Shipping</h6>-->
<!--                            <h6 class="font-weight-medium">$10</h6>-->
<!--                        </div>-->
                    </div>
                    <div class="card-footer border-secondary bg-transparent">
                        <div class="d-flex justify-content-between mt-2">
                            <h5 class="font-weight-bold">Total</h5>
                            <h5 class="font-weight-bold">{{total}}</h5>
                        </div>
                        <a href="{% url 'checkout' %}" class="btn btn-block btn-primary my-3 py-3">Proceed To Checkout</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Cart End -->


{% endblock %}
{% block body %}

{% endblock %}
{% block footer %}
    {% include 'core/footer.html' %}
{% endblock %}

ecommerce/templates/core/contact.html
{% extends 'core/layout.html' %}
{% load static %}
{% block title %} Contacts
{% endblock %}

{% block content %}

    <!-- Contact Start -->
    <div class="container-fluid pt-5">
        <div class="text-center mb-4">
            <h2 class="section-title px-5"><span class="px-2">Contact For Any Queries</span></h2>
        </div>
        <div class="row px-xl-5">
            <div class="col-lg-7 mb-5">
                <div class="contact-form">
                    <div id="success">
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-success" role="alert">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <form name="sentMessage" action="{% url 'core:contact' %}" method="POST">
                        {% csrf_token %}
                        <div class="control-group">
                            <input type="text" class="form-control" id="name" placeholder="Your Name" name="name"
                                required="required" data-validation-required-message="Please enter your name" />
                            <p class="help-block text-danger"></p>
                        </div>
                        <div class="control-group">
                            <input type="email" class="form-control" id="email" placeholder="Your Email" name="email"
                                required="required" data-validation-required-message="Please enter your email" />
                            <p class="help-block text-danger"></p>
                        </div>
                        <div class="control-group">
                            <input type="text" class="form-control" id="subject" placeholder="Subject" name="subject"
                                required="required" data-validation-required-message="Please enter a subject" />
                            <p class="help-block text-danger"></p>
                        </div>
                        <div class="control-group">
                            <textarea class="form-control" rows="15" id="message" placeholder="Message" name="message"
                                required="required"
                                data-validation-required-message="Please enter your message"></textarea>
                            <p class="help-block text-danger"></p>
                        </div>
                        <div>
                            <button class="btn btn-primary py-2 px-4" type="submit" id="sendMessageButton">Send
                                Message</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-lg-5 mb-5">
                {{ setting.contact|safe }}
            </div>
        </div>
    </div>
    <!-- Contact End -->
{% endblock %}
{% block body %}

{% endblock %}
{% block footer %}
    {% include 'core/footer.html' %}
{% endblock %}

ecommerce/templates/core/footer.html
{% load static %}
    <!-- Footer Start -->
    <div class="container-fluid bg-secondary text-dark mt-5 pt-5">
        <div class="row px-xl-5 pt-5">
            <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
                <a href="" class="text-decoration-none">
                    <h1 class="mb-4 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border border-white px-3 mr-1">E</span>Shopper</h1>
                </a>
                <p>Dolore erat dolor sit lorem vero amet. Sed sit lorem magna, ipsum no sit erat lorem et magna ipsum dolore amet erat.</p>
                <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>123 Street, New York, USA</p>
                <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@example.com</p>
                <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
            </div>
            <div class="col-lg-8 col-md-12">
                <div class="row">
                    <div class="col-md-4 mb-5">
                        <h5 class="font-weight-bold text-dark mb-4">Quick Links</h5>
                        <div class="d-flex flex-column justify-content-start">
                            <a class="text-dark mb-2" href="{% url 'core:index' %}"><i class="fa fa-angle-right mr-2"></i>Home</a>
                            <a class="text-dark mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Shop Detail</a>
                            <a class="text-dark mb-2" href="{% url 'core:cart' %}"><i class="fa fa-angle-right mr-2"></i>Shopping Cart</a>
                            <a class="text-dark mb-2" href="{% url 'core:checkout' %}"><i class="fa fa-angle-right mr-2"></i>Checkout</a>
                            <a class="text-dark" href="{% url 'core:contact' %}"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                        </div>
                    </div>
                    <div class="col-md-4 mb-5">
                        <h5 class="font-weight-bold text-dark mb-4">Quick Links</h5>
                        <div class="d-flex flex-column justify-content-start">
                            <a class="text-dark mb-2" href="{% url 'core:index' %}"><i class="fa fa-angle-right mr-2"></i>Home</a>
                            <a class="text-dark mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Shop Detail</a>
                            <a class="text-dark mb-2" href="{% url 'core:cart' %}"><i class="fa fa-angle-right mr-2"></i>Shopping Cart</a>
                            <a class="text-dark mb-2" href="{% url 'core:checkout' %}"><i class="fa fa-angle-right mr-2"></i>Checkout</a>
                            <a class="text-dark" href="{% url 'core:contact' %}"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                        </div>
                    </div>
                    <div class="col-md-4 mb-5">
                        <h5 class="font-weight-bold text-dark mb-4">Newsletter</h5>
                        <form action="">
                            <div class="form-group">
                                <input type="text" class="form-control border-0 py-4" placeholder="Your Name" required="required" />
                            </div>
                            <div class="form-group">
                                <input type="email" class="form-control border-0 py-4" placeholder="Your Email"
                                    required="required" />
                            </div>
                            <div>
                                <button class="btn btn-primary btn-block border-0 py-3" type="submit">Subscribe Now</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row border-top border-light mx-xl-5 py-4">
            <div class="col-md-6 px-xl-0">
                <p class="mb-md-0 text-center text-md-left text-dark">
                    &copy; <a class="text-dark font-weight-semi-bold" href="#">Your Site Name</a>. All Rights Reserved. Designed
                    by
                    <a class="text-dark font-weight-semi-bold" href="https://htmlcodex.com">HTML Codex</a>
                </p>
            </div>
            <div class="col-md-6 px-xl-0 text-center text-md-right">
                <img class="img-fluid" src="{% static 'assets/' %}img/payments.png" alt="">
            </div>
        </div>
    </div>
    <!-- Footer End -->

ecommerce/templates/core/header.html
{% load mptt_tags %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"> </script>
<!-- jQuery UI !-->
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
    <script>

      $(function() {
        $("#query").autocomplete({
          source: "/search_auto/",
          select: function (event, ui) { //item selected
            AutoCompleteSelectHandler(event, ui)
          },
          minLength: 1,
        });
      });

      function AutoCompleteSelectHandler(event, ui)
      {
        var selectedObj = ui.item;
      }

    </script>
    <!-- Topbar Start -->
    <div class="container-fluid">
        <div class="row bg-secondary py-2 px-xl-5">
            <div class="col-lg-6 d-none d-lg-block">
                <div class="d-inline-flex align-items-center">
                    <a class="text-dark" href="">FAQs</a>
                    <span class="text-muted px-2">|</span>
                    <a class="text-dark" href="">Help</a>
                    <span class="text-muted px-2">|</span>
                    <a class="text-dark" href="">Support</a>
                </div>
            </div>
            <div class="col-lg-6 text-center text-lg-right">
                <div class="d-inline-flex align-items-center">
                    <a class="text-dark px-2" href="">
                        <i class="fab fa-facebook-f"></i>
                    </a>
                    <a class="text-dark px-2" href="">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <a class="text-dark px-2" href="">
                        <i class="fab fa-linkedin-in"></i>
                    </a>
                    <a class="text-dark px-2" href="">
                        <i class="fab fa-instagram"></i>
                    </a>
                    <a class="text-dark pl-2" href="">
                        <i class="fab fa-youtube"></i>
                    </a>
                </div>
            </div>
        </div>
        <div class="row align-items-center py-3 px-xl-5">
            <div class="col-lg-3 d-none d-lg-block">
                <a href="{% url 'core:index' %}" class="text-decoration-none">
                    <h1 class="m-0 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border px-3 mr-1">{{setting.company}}</span></h1>
                </a>
            </div>
            <!--  Search  -->
            <div class="col-lg-6 col-6 text-left">
                <form method="POST" action="{% url 'core:search' %}">
                    {% csrf_token %}
                    <div class="input-group">
                        <input id="query" name="query" type="text" class="form-control" placeholder="Search for products">
                        <div class="input-group-append">
                            <select id="cat" name="cat" class="input-group-text">
                                <option value="0">All Categories</option>
                                    {% recursetree category %}
                                        {% if node.is_leaf_node %}
                                            <option value="{{node.id}}">{{node.title}}</option>
                                        {% else %}
                                            <optgroup label="{{node.title}}">{{children}}</optgroup>
                                        {% endif %}
                                    {% endrecursetree %}
                            </select>
                            <span class="input-group-text bg-transparent text-primary">
                                <button type="submit"><i class="fa fa-search"></i></button>
                            </span>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-3 col-6 text-right">
                <a href="" class="btn border">
                    <i class="fas fa-heart text-primary"></i>
                    <span class="badge">0</span>
                </a>
                <a href="/order/shopcart/" class="btn border">
                    <i class="fas fa-shopping-cart text-primary"></i>
                    <span class="badge">{{shopcart|length}}</span>
                    <span>{{ total }}</span>
                </a>
            </div>
        </div>
    </div>
    <!-- Topbar End -->

ecommerce/templates/core/index.html
{% extends 'core/layout.html' %}
{% load static %}
{% block title %} Main Page
{% endblock %}
{% block slider %}
    {% include 'core/slider.html' %}
{% endblock %}
{% block sidebar %}
    {% include 'core/sidebar.html' %}
{% endblock %}
{% block content %}
    {% include 'core/content.html' %}
{% endblock %}
{% block body %}

{% endblock %}
{% block footer %}
    {% include 'core/footer.html' %}
{% endblock %}

ecommerce/templates/core/layout.html
<!DOCTYPE html>
{% load static %}
{% load mptt_tags %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>{% block title %} {% endblock %}</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="{{ setting.keywords}}" name="keywords">
    <meta content="{{ setting.description }}" name="description">

    <!-- Favicon -->
    <link href="{% static 'assets/img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'assets/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
    {% block head %}
    {% endblock %}
</head>

<body>
    {% include 'core/header.html' %}
    {% block header %}
    {% endblock %}
    <!-- Navbar Start -->
    <div class="container-fluid mb-5">
        <div class="row border-top px-xl-5">
            <div class="col-lg-3 d-none d-lg-block">
                {% block sidebar %}

                {% endblock %}
            </div>
            <div class="col-lg-9">

                <nav class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0">
                    <a href="{% url 'core:index' %}" class="text-decoration-none d-block d-lg-none">
                        <h1 class="m-0 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border px-3 mr-1">E</span>Shopper</h1>
                    </a>
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                        <div class="navbar-nav mr-auto py-0">
                            <a href="{% url 'core:index' %}" class="nav-item nav-link active">Home</a>
<!--                            <a href="#" class="nav-item nav-link">Shop Detail</a>-->
                            {% if request.user.is_superuser %}
                            <a href="/admin/" class="nav-item nav-link">Admin</a>
                            {% endif %}
<!--                            <div class="nav-item dropdown">-->
<!--                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Pages</a>-->
<!--                                <div class="dropdown-menu rounded-0 m-0">-->
<!--                                    <a href="{% url 'core:cart' %}" class="dropdown-item">Shopping Cart</a>-->
<!--                                    <a href="{% url 'core:checkout' %}" class="dropdown-item">Checkout</a>-->
<!--                                </div>-->
<!--                            </div>-->
                            <a href="{% url 'core:contact' %}" class="nav-item nav-link">Contact</a>
                        </div>
                        <div class="navbar-nav ml-auto py-0">
                            {% if request.user.is_authenticated %}
                                <a href="{% url 'user_index' %}" class="nav-item nav-link">Profile</a>
                                <a href="{% url 'logout' %}" class="nav-item nav-link">Logout</a>
                            {% else %}
                                <a href="{% url 'login' %}" class="nav-item nav-link">Login</a>
                                <a href="{% url 'register' %}" class="nav-item nav-link">Register</a>
                            {% endif %}
                        </div>
                    </div>
                </nav>
                {% block slider %}
                {% endblock %}
            </div>
        </div>
    </div>
    <!-- Navbar End -->
    {% block content %}
    {% endblock %}
    {% block body %}
    {% endblock %}
    {% block footer %}
    {% endblock %}
    <!-- Back to Top -->
        <a href="#" class="btn btn-primary back-to-top"><i class="fa fa-angle-double-up"></i></a>

    <!-- JavaScript Libraries -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'assets/lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'assets/lib/owlcarousel/owl.carousel.min.js' %}"></script>

    <!-- Contact Javascript File -->
    <script src="{% static 'assets/mail/jqBootstrapValidation.min.js' %}"></script>
    <script src="{% static 'assets/mail/contact.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'assets/js/main.js' %}"></script>
</body>

</html>