ecommerce/core/urls.py
from django.urls import path, include

from .views import index, contact, cart, checkout, detail, shop, search, search_auto

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
    path('contact/', contact, name='contact'),
    path('cart/', cart, name='cart'),
    path('checkoout/', checkout, name='checkout'),
    path('shop/', shop, name='shop'),
    path('search/', search, name='search'),
    path('search_auto/', search_auto, name='search_auto'),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('p/', include('product.urls')),
    path('order/', include('order.urls')),
    path('user/', include('users.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/users/urls.py
from django.urls import path
from .views import index, logout_func, login_func, register_func

urlpatterns = [
    path('', index, name='user_index'),
    path('login/', login_func, name='login'),
    path('logout/', logout_func, name='logout'),
    path('register/', register_func, name='register'),
]

ecommerce/users/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.safestring import mark_safe


# Create your models here.


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=20, blank=True)
    address = models.CharField(max_length=150, blank=True)
    city = models.CharField(max_length=150, blank=True)
    country = models.CharField(max_length=150, blank=True)
    image = models.ImageField(upload_to='images/users/', default='images/users/default.jpg')

    def __str__(self):
        return f'{self.user.username}'

    def user_name(self):
        return f'{self.user.first_name} {self.user.last_name} {self.user.username}'

    def image_tag(self):
        if self.image:
            return mark_safe(f'<img src="{self.image.url}" width="auto" height="50px" />')
        else:
            return 'No Image'

ecommerce/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegistrationForm(UserCreationForm):
    username = forms.CharField(max_length=30, label='Username: ')
    email = forms.EmailField(max_length=200, label='Email: ')
    first_name = forms.CharField(max_length=150, label='First Name: ')
    last_name = forms.CharField(max_length=150, label='Last Name: ')

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']

ecommerce/users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.shortcuts import render

from core.models import Setting
from order.models import ShopCart
from product.models import Category
from .forms import RegistrationForm
from .models import UserProfile


# Create your views here.


def index(request):
    setting = Setting.objects.filter(status=True).first()
    category = Category.objects.all()
    current_shopcart = ShopCart.objects.filter(user_id=request.user.id)
    total = 0
    quantity = 0
    if request.user.is_authenticated:
        current_shopcart = ShopCart.objects.filter(user_id=request.user.id)
        for sc in current_shopcart:
            total += sc.product.price * sc.quantity
            quantity += sc.quantity

    context = {
        'setting': setting,
        'category': category,
        'shopcart': current_shopcart,
        'total': int(total),
        'quantity': quantity,
    }
    return render(request, 'users/user_profile.html', context)


def login_func(request):
    setting = Setting.objects.filter(status=True).first()
    category = Category.objects.all()
    total = 0
    quantity = 0
    current_shopcart = None

    if request.user.is_authenticated:
        current_shopcart = ShopCart.objects.filter(user_id=request.user.id)
        for sc in current_shopcart:
            total += sc.product.price * sc.quantity
            quantity += sc.quantity

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        our_user = authenticate(request, username=username, password=password)

        if our_user is not None:
            login(request, our_user)
            return HttpResponseRedirect('/')
        else:
            messages.warning(request, 'Login error. Check username or password')
            return HttpResponseRedirect('/users/login')

    context = {
        'setting': setting,
        'category': category,
        'shopcart': current_shopcart,
        'total': int(total),
        'quantity': quantity,
    }
    return render(request, 'users/login_form.html', context)


def logout_func(request):
    logout(request)
    return HttpResponseRedirect('/')


def register_func(request):
    setting = Setting.objects.filter(status=True).first()
    category = Category.objects.all()
    current_shopcart = ShopCart.objects.filter(user_id=request.user.id)
    total = 0
    quantity = 0
    if request.user != 'AnonymousUser':
        current_shopcart = ShopCart.objects.filter(user_id=request.user.id)
        for sc in current_shopcart:
            total += sc.product.price * sc.quantity
            quantity += sc.quantity
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            our_user = authenticate(request, username=username, password=password)
            login(request, our_user)
            data = UserProfile()
            data.user_id = our_user.id
            data.image = 'images/users/default.jpg'
            data.save()
            return HttpResponseRedirect('/')

    form = RegistrationForm()
    context = {'setting': setting, 'category': category,
               'shopcart': current_shopcart,
               'total': int(total), 'quantity': quantity,
               'form': form,
               }
    return render(request, 'users/registration_form.html', context)

ecommerce/templates/users/login_form.html
{% extends 'core/layout.html' %}
{% load static %}
{% block title %} Authentication {% endblock %}

{% block sidebar %}{% include 'core/sidebar.html' %}{% endblock %}

{% block content %}
<!-- BREADCRUMB -->
	<div id="breadcrumb">
		<div class="container">
			<ul class="breadcrumb">
				<li><a href="{% url 'core:index' %}">Home</a></li>
				<li class="active">Authentication </li>
			</ul>
		</div>
	</div>
	<!-- /BREADCRUMB -->

	<!-- section -->
	<div class="section">
		{% if messages %}
			{% for message in messages %}
			<div class="alert alert-info" role="alert">
				{{ message }}
			</div>
			{% endfor %}
		{% endif %}
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="col-md-6">
				<div class="row">
					<form id="checkout-form" class="clearfix" method="post">
						{% csrf_token %}
						<div class="form-group">
							<input class="input" type="text" name="username" placeholder="Enter username">
						</div>
						<div class="form-group">
							<input class="input" type="password" name="password" placeholder="Enter your password">
						</div>
						<button class="primary-btn" type="submit"> Login </button>
					</form>
				</div>
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
	<!-- /section -->
{% endblock %}
{% block footer %}{% include 'core/footer.html' %}{% endblock %}

ecommerce/templates/users/registration_form.html
{% extends 'core/layout.html' %}
{% load static %}
{% block title %}Registration {% endblock %}

{% block sidebar %}{% include 'core/sidebar.html' %}{% endblock %}

{% block content %}
<!-- BREADCRUMB -->
<div id="breadcrumb">
    <div class="container">
        <ul class="breadcrumb">
            <li><a href="{% url 'core:index' %}">Home</a></li>
            <li class="active">Registration</li>
        </ul>
    </div>
</div>
<!-- /BREADCRUMB -->

<!-- section -->
<div class="section">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-info" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="col-md-6">
            <div class="row">
                <form id="checkout-form" class="clearfix" method="post">
                    {% csrf_token %}
                    <h4 class="footer-header">Username:</h4>
                    <input class="input" type="text" name="username" maxlength="30" autofocus required id="id_username">
                    <br>
                    <h4 class="footer-header">Email:</h4>
                    <input class="input" type="email" name="email" maxlength="200" required id="id_email">
                            <br>
                    <h4 class="footer-header">First name: :</h4>
                    <input class="input" type="text" name="first_name" maxlength="150" required id="id_first_name">
                    <br>
                    <h4 class="footer-header">Last name: :</h4>

                    <input class="input" type="text" name="last_name" maxlength="150" required id="id_last_name">
                    <br>
                    <h4 class="footer-header">Password:</h4>
                    <input class="input" type="password" name="password1" autocomplete="new-password" required
                           id="id_password1">
                    <br>

                    <span class="helptext"><ul><li>Your password can’t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can’t be a commonly used password.</li><li>Your password can’t be entirely numeric.</li></ul></span>
                    <br>

                    <h4 class="footer-header">Password confirmation:</h4>
                    <input class="input" type="password" name="password2" autocomplete="new-password" required
                           id="id_password2">

                    <br>
                    <span class="helptext">Enter the same password as before, for verification.</span>
<br>
                    <button class="primary-btn" type="submit"> Register</button>
                </form>
            </div>
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>
<!-- /section -->
{% endblock %}
{% block footer %}{% include 'core/footer.html' %}{% endblock %}

ecommerce/templates/users/user_panel.html
<div class="billing-details">

    <div class="section-title">
        <h3 class="title"> User panel</h3>
    </div>
    <div class="aside">
        <ul class="list-links">
            <li><a href="/user"> User profile</a></li>
            <li><a href="/user/orders"> My orders</a></li>
            <li><a href="/user/order_products"> My ordered products</a></li>
            <li><a href="/user/comments"> My comments </a></li>
            <li><a href="/user/favorites"> My favorites </a></li>
            <br>
            <li><a href="{% url 'logout' %}"> Logout </a></li>
         </ul>
    </div>
</div>

ecommerce/templates/users/user_profile.html
{% extends 'core/layout.html' %}
{% load static %}
{% block title %} 9 Bit - about{% endblock %}

{% block sidebar %}{% include 'core/sidebar.html' %}{% endblock %}

{% block content %}
<!-- BREADCRUMB -->
	<div id="breadcrumb">
		<div class="container">
			<ul class="breadcrumb">
				<li><a href="{% url 'core:index' %}">Home</a></li>
				<li class="active">About us</li>
			</ul>
		</div>
	</div>
	<!-- /BREADCRUMB -->

	<!-- section -->
	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="col-md-3">
				{% include 'users/user_panel.html' %}
			</div>
			<div class="col-md-9">
				<h1> Тут будет информация профиля </h1>
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
	<!-- /section -->
{% endblock %}
{% block footer %}{% include 'core/footer.html' %}{% endblock %}